########################################
# PalHUB::Server by dekitarpg@gmail.com
########################################

# 
# set the compose version information, shouldnt be required 
# if you have the latest versions of docker/docker-compose <3
# 
version: '3.9' 

# 
# defines the actual compose configuration to use 
# switch this for ./docker.compose.minimal.yml
# if you want to launch the minimal config using
# `docker compose up -d`
# or similar..
# 
include:
  - ./docker.compose.default.yml
