########################################
# PalHUB::Server by dekitarpg@gmail.com
########################################
services:
  # 
  # admin: 
  # see ./admin.compose.yml
  # 
  admin:
    extends: #extend upon the base admin.compose file
      file: ./admin.compose.yml
      service: admin
    build: # use the dev.dockerfile as we are dev
      context: ../../admin
      dockerfile: ./dev.dockerfile
    volumes: #additional volumes for hot reloading
      - ../../admin:/app
      - /app/node_modules
      - /app/.next
