########################################
# PalHUB::Server by dekitarpg@gmail.com
########################################
services: 
  # 
  # admin: 
  # provides a frontend ui for users+admins
  # 
  admin:
    build: ../../admin
    container_name: palhub-admin-server
    stop_grace_period: ${PALWORLD_GRACEPERIOD}
    restart: unless-stopped
    image: palhub-admin-server
    volumes:
      # mount env files so we can edit/reset from ui
      - ../../.env:/app/mounted-env.env 
      - ../../.default.env:/app/default-env.env
      # mount directory for storing logs + backups
      - ../../logs:/app/logs 
      - ../../backups:/app/backups
      # mount the actual game server folder
      - ../../server/palworld:/app/PalServer
      # additional mounts for system id + time
      - /etc/machine-id:/etc/machine-id:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ../../.env
    networks:
      - palhubnet
