########################################
# PalHUB::Server by dekitarpg@gmail.com
########################################
services: 
  # 
  # nginx: 
  # handles routing for the various other services 
  # 
  nginx:
    build: ../../nginx
    # image: nginx:mainline-alpine 
    container_name: palhub-nginx
    restart: unless-stopped
    ports:
      - 80:80   # website: basic http site
      - 443:443 # website: ssl enabled site # ! uncomment when/if ssl support added
      # # palworld: main server communication line 
      - ${PALWORLD_GAME_PORT}:8211/udp 
      # # palworld: allows server to show up in the community servers tab 
      - ${PALWORLD_COMM_PORT}:27015/udp 
      # palworld: allows rcon to communicate with server
      - ${PALWORLD_RCON_PORT}:25575/tcp
      # Palworld: rest api port
      - ${PALWORLD_REST_PORT}:8212/tcp
    volumes:
      - nginx_data_container:/var/www/html
      - ../../server/palworld:/app/palworld
      - ../../config/nginx:/etc/nginx
      - ../../logs/nginx:/var/log/nginx
      - ../../logs:/app/logs
    depends_on:
      - palworld
      - netdata
    env_file:
      - ../../.env
    networks:
      - palhubnet

# 
# defines named volumes used by nginx
# 
volumes:
  nginx_data_container:
