########################################
# PalHUB::Server by dekitarpg@gmail.com
########################################
services: 
  # 
  # palworld: 
  # the service for the main palworld game server
  # 
  palworld:
    build: ../../server
    container_name: palhub-game-server
    stop_grace_period: ${PALWORLD_GRACEPERIOD}
    restart: ${PALWORLD_RESTARTTYPE}
    image: palhub-game-server
    volumes:
      - ../../logs:/app/logs # mount directory for storing logs
      - ../../logs/steam:/home/steam/.steam/steam/logs # add steam logs
      # - ../../server/palworld:/app/PalServer/Pal
      - ../../server/palworld:/app/PalServer
      - ../../backups:/app/backups
      - /etc/machine-id:/etc/machine-id:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ../../.env
    networks:
      - palhubnet
